# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
import cv2, imutils
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(450, 420, 170, 89))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 4, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tb_h = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.tb_h.setOrientation(QtCore.Qt.Horizontal)
        self.tb_h.setObjectName("tb_h")
        self.verticalLayout_4.addWidget(self.tb_h)
        self.tb_s = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.tb_s.setOrientation(QtCore.Qt.Horizontal)
        self.tb_s.setObjectName("tb_s")
        self.verticalLayout_4.addWidget(self.tb_s)
        self.tb_v = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.tb_v.setOrientation(QtCore.Qt.Horizontal)
        self.tb_v.setObjectName("tb_v")
        self.verticalLayout_4.addWidget(self.tb_v)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(230, 420, 172, 94))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.tb_r = QtWidgets.QSlider(self.verticalLayoutWidget_5)
        self.tb_r.setOrientation(QtCore.Qt.Horizontal)
        self.tb_r.setObjectName("tb_r")
        self.verticalLayout_5.addWidget(self.tb_r)



        self.tb_g = QtWidgets.QSlider(self.verticalLayoutWidget_5)
        self.tb_g.setOrientation(QtCore.Qt.Horizontal)
        self.tb_g.setObjectName("tb_g")
        self.verticalLayout_5.addWidget(self.tb_g)
        self.tb_b = QtWidgets.QSlider(self.verticalLayoutWidget_5)
        self.tb_b.setOrientation(QtCore.Qt.Horizontal)
        self.tb_b.setObjectName("tb_b")
        self.verticalLayout_5.addWidget(self.tb_b)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(10, 30, 291, 331))
        self.screen.setFrameShape(QtWidgets.QFrame.Box)
        self.screen.setLineWidth(3)
        self.screen.setObjectName("screen")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(90, 410, 75, 23))
        self.btn_open.setObjectName("btn_open")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(830, 480, 75, 23))
        self.btn_save.setObjectName("btn_save")
        self.screen_2 = QtWidgets.QLabel(self.centralwidget)
        self.screen_2.setGeometry(QtCore.QRect(320, 30, 291, 331))
        self.screen_2.setFrameShape(QtWidgets.QFrame.Box)
        self.screen_2.setLineWidth(3)
        self.screen_2.setObjectName("screen_2")
        self.screen_3 = QtWidgets.QLabel(self.centralwidget)
        self.screen_3.setGeometry(QtCore.QRect(630, 30, 291, 331))
        self.screen_3.setFrameShape(QtWidgets.QFrame.Box)
        self.screen_3.setLineWidth(3)
        self.screen_3.setObjectName("screen_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 370, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 370, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(760, 370, 47, 16))
        self.label_9.setObjectName("label_9")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(195, 430, 21, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(420, 420, 21, 81))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_6.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Giá trị khởi tạo cho các slider HSV
        self.ilowH = 0
        self.ihighH = 179
        self.ilowS = 0
        self.ihighS = 255
        self.ilowV = 0
        self.ihighV = 255
        #add them
        #lowh
        self.tb_r.setRange(0,179)
        self.tb_r.setValue(self.ilowH)
        self.tb_r.valueChanged.connect(self.update_value)
        #upper h
        self.tb_h.setRange(0, 179)
        self.tb_h.setValue(self.ihighH)
        self.tb_r.valueChanged.connect(self.update_value)
        #low s
        self.tb_g.setRange(0, 255)
        self.tb_g.setValue(self.ilowS)
        self.tb_g.valueChanged.connect(self.update_value)
        #upper s
        self.tb_s.setRange(0, 255)
        self.tb_s.setValue(self.ihighS)
        self.tb_s.valueChanged.connect(self.update_value)
        #low v
        self.tb_b.setRange(0, 255)
        self.tb_b.setValue(self.ilowV)
        self.tb_b.valueChanged.connect(self.update_value)
        #uppper v
        self.tb_v.setRange(0, 255)
        self.tb_v.setValue(self.ihighV)
        self.tb_v.valueChanged.connect(self.update_value)


        self.retranslateUi(MainWindow)
        self.btn_open.clicked.connect(self.loadImage)
        self.btn_save.clicked.connect(self.savePhoto)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def loadImage(self):
        """ This function will load the user selected image
            and set it to label using the setPhoto function
        """
        self.filename = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
        self.image = cv2.imread(self.filename)




        self.setPhoto(self.image)

    def setPhoto(self, image):
        """ This function will take image input and resize it
            only for display purpose and convert it to QImage
            to set at the label.
        """

        image = imutils.resize(image, width=291)
        #Resize the image to 291x331
        #image = cv2.resize(image, (291, 331))

        self.tmp = image
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1], frame.shape[0], frame.strides[0], QImage.Format_RGB888)  #stride la tong so pixel truot qua
        self.screen.setPixmap(QtGui.QPixmap.fromImage(image))

        # Store the dimensions of the image for later use
        self.image_width = image.width()
        self.image_height = image.height()

    def savePhoto(self ):
        """ This function will save the image"""
        # here provide the output file name
        # lets say we want to save the output as a time stamp
        # uncomment the two lines below

        # import time
        # filename = 'Snapshot '+str(time.strftime("%Y-%b-%d at %H.%M.%S %p"))+'.png'

        # Or we can give any name such as output.jpg or output.png as well
        # filename = 'Snapshot.png'

        # Or a much better option is to let user decide the location and the extension
        # using a file dialog.

        filename = QFileDialog.getSaveFileName(filter="JPG(*.jpg);;PNG(*.png);;TIFF(*.tiff);;BMP(*.bmp)")[0]

        cv2.imwrite(filename, self.processedimg)
        print('Image saved as:', self.filename)


    def update_value(self):

        if self.image is None:
            return

        # Lấy giá trị từ các slider
        self.ilowH = self.tb_r.value()
        self.ihighH = self.tb_h.value()
        self.ilowS = self.tb_g.value()
        self.ihighS = self.tb_s.value()
        self.ilowV = self.tb_b.value()
        self.ihighV = self.tb_v.value()
        self.image = imutils.resize(self.image, width=291)
        # Chuyển đổi sang không gian màu HSV
        hsv = cv2.cvtColor(self.image, cv2.COLOR_BGR2HSV)

        # Tạo mask với các giá trị HSV hiện tại
        lower_hsv = np.array([self.ilowH, self.ilowS, self.ilowV])
        upper_hsv = np.array([self.ihighH, self.ihighS, self.ihighV])
        mask = cv2.inRange(hsv, lower_hsv, upper_hsv)

        # Convert mask to QImage
        mask_qimage = QImage(mask.data, mask.shape[1], mask.shape[0], mask.strides[0], QImage.Format_Grayscale8)

        self.screen_2.setPixmap(QtGui.QPixmap.fromImage(mask_qimage))

        # Áp dụng phép toán bitwise AND để lấy phần của hình ảnh nằm trong khoảng giá trị HSV
        result = cv2.bitwise_and(self.image, self.image, mask=mask)



        # Chuyển đổi kết quả bitwise sang dạng QImage để hiển thị
        result_rgb = cv2.cvtColor(result, cv2.COLOR_BGR2RGB)

        result_qimage = QImage(result_rgb.data, result_rgb.shape[1], result_rgb.shape[0], result_rgb.strides[0],
                               QImage.Format_RGB888)
        self.processedimg = result

        self.screen_3.setPixmap(QtGui.QPixmap.fromImage(result_qimage))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.screen.setText(_translate("MainWindow", "display"))
        self.btn_open.setText(_translate("MainWindow", "open"))
        self.btn_save.setText(_translate("MainWindow", "save"))
        self.screen_2.setText(_translate("MainWindow", "display"))
        self.screen_3.setText(_translate("MainWindow", "display"))
        self.label_7.setText(_translate("MainWindow", "orgin"))
        self.label_8.setText(_translate("MainWindow", "mask"))
        self.label_9.setText(_translate("MainWindow", "result"))
        self.label.setText(_translate("MainWindow", "l_h"))
        self.label_2.setText(_translate("MainWindow", "l_s"))
        self.label_3.setText(_translate("MainWindow", "l_v"))
        self.label_4.setText(_translate("MainWindow", "u_h"))
        self.label_5.setText(_translate("MainWindow", "u-s"))
        self.label_6.setText(_translate("MainWindow", "u_v"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
